name: Mirror to Gitea via ngrok

on:
  workflow_dispatch:
  push:
    branches: ["*"]

jobs:
  sync-to-gitea:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to Gitea (via ngrok)
        env:
          GITEA_USERNAME_ENC: vineeth25d60%40gmail.com
          GITEA_PASSWORD: 102a0eb0655ee553e1e939670104dee2ff256135
          GITEA_URL: 9e233262196c.ngrok-free.app/vineeth/auto-update-ami-references.git
        run: |
          git remote add gitea "https://${GITEA_USERNAME_ENC}:${GITEA_PASSWORD}@${GITEA_URL}"
          git push --mirror gitea
