name: Update AMI ID in cluster.yml

on:
  workflow_dispatch:

jobs:
  update-ami:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    env:
      PIPELINE_NAME: "amitest" # <-- Update this to match your actual pipeline name
      CLUSTER_YML_PATH: "Definitions/clusters.yml" # <-- Update this to match your actual file path
      #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install boto3 pyyaml ruamel.yaml requests

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Get latest AMI ID
        env:
          AWS_REGION: "us-east-1"
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python3 scripts/update_cluster_ami.py
