name: Update AMI ID in cluster.yml

on:
  workflow_dispatch:

jobs:
  update-ami:
    runs-on: ubuntu-latest

    env:
      PIPELINE_NAME: "amitest" # <-- Update this to match your actual pipeline name
      CLUSTER_YML_PATH: "Definitions/clusters.yml" # <-- Update this to match your actual file path

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install boto3 pyyaml ruamel.yaml

      - name: Run AMI updater
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
        run: |
          python3 scripts/update_cluster_ami.py
